ElectronicJournal_WEB/Controllers/TeacherHomePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ElectronicJournal_WEB.Context;
using ElectronicJournal_WEB.Models;
using ElectronicJournal_WEB.Models.DatabaseModel;
using ElectronicJournal_WEB.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ElectronicJournal_WEB.Controllers
{
    public class TeacherHomePageController : Controller
    {
        Users _user;
        ElectronicalJournalContext db;

        public TeacherHomePageController()
        {
            _user = new Users();
            db = new ElectronicalJournalContext();
        }

        public IActionResult Index()
        {
            _user = db.Users.Find(UserSession.GetUserId);
            List<IndexTeacherViewModel> lessonList = new List<IndexTeacherViewModel>();

            lessonList = (from tch in db.Teachers
                          join tc_ls in db.TeacherLessons on tch.TeacherId equals tc_ls.TeacherId
                          into tc_lsDatails
                          from tc_lsDat in tc_lsDatails.DefaultIfEmpty()
                          join ls in db.Lessons on tc_lsDat.LessonId equals ls.LessonId
                          into lsDatails
                          from lsDat in lsDatails.DefaultIfEmpty()
                          join sbj in db.Subjects on lsDat.SubjectId equals sbj.SubjectId
                          join lt in db.LessonTypes on lsDat.LessonTypeId equals lt.LessonTypeId
                          into ltDatails
                          from ltDat in ltDatails.DefaultIfEmpty()
                          join ts in db.TimeSchedules on lsDat.TimeScheduleId equals ts.TimeScheduleId
                          into tsDatails
                          from tsDat in tsDatails.DefaultIfEmpty()
                          join cls in db.Classrooms on lsDat.ClassroomId equals cls.ClassroomId
                          into clsDatail
                          from clsDat in clsDatail.DefaultIfEmpty()
                          join build in db.Buildings on clsDat.BuildingId equals build.BuildingId
                          into buildDatail
                          from buidDat in buildDatail.DefaultIfEmpty()
                          join gr_ls in db.GroupLessons on lsDat.LessonId equals gr_ls.LessonId
                          join gr in db.Groups on gr_ls.GroupId equals gr.GroupId
                          where tch.UserId == UserSession.GetUserId
                          where lsDat.Date >= DateTime.Today
                          orderby lsDat.Date
                          select new IndexTeacherViewModel
                          {
                              LessonId = lsDat.LessonId,
                              GroupName = gr.GroupName,
                              LessonDate = lsDat.Date.ToLongDateString(),
                              LessonTime = tsDat.TimeInterval,
                              SubjectName = sbj.SubjectName,
                              LessonType = ltDat.LessonTypeName,
                              ClassroomName = buidDat.BuildingName + " " + clsDat.ClassroomName
                          }).ToList();

            return View(lessonList);
        }
        //выбор группы, которую хочет оценить преподаватель
        [HttpGet]
        public IActionResult StudentAssessment()
        {
            List<Groups> groups = new List<Groups>();
            groups = (from tch in db.Teachers
                      join tc_ls in db.TeacherLessons on tch.TeacherId equals tc_ls.TeacherId
                      into tc_lsDatails
                      from tc_lsDat in tc_lsDatails.DefaultIfEmpty()
                      join ls in db.Lessons on tc_lsDat.LessonId equals ls.LessonId
                      into lsDatails
                      from lsDat in lsDatails.DefaultIfEmpty()
                      join gr_ls in db.GroupLessons on lsDat.LessonId equals gr_ls.LessonId
                      join gr in db.Groups on gr_ls.GroupId equals gr.GroupId
                      select new Groups
                      {
                          GroupId = gr.GroupId,
                          GroupName = gr.GroupName,
                          YearFormationGroup = gr.YearFormationGroup
                      }).Distinct().ToList();

            return View(groups);
        }
        //формируем список занятий, проведенных в данной группе
        public IActionResult GroupsLessons(int id) //на входе получаем id группы
        {
            List<IndexTeacherViewModel> lessonList = new List<IndexTeacherViewModel>();

            lessonList = (from tch in db.Teachers
                          join tc_ls in db.TeacherLessons on tch.TeacherId equals tc_ls.TeacherId
                          into tc_lsDatails
                          from tc_lsDat in tc_lsDatails.DefaultIfEmpty()
                          join ls in db.Lessons on tc_lsDat.LessonId equals ls.LessonId
                          into lsDatails
                          from lsDat in lsDatails.DefaultIfEmpty()
                          join sbj in db.Subjects on lsDat.SubjectId equals sbj.SubjectId
                          join lt in db.LessonTypes on lsDat.LessonTypeId equals lt.LessonTypeId
                          into ltDatails
                          from ltDat in ltDatails.DefaultIfEmpty()
                          join ts in db.TimeSchedules on lsDat.TimeScheduleId equals ts.TimeScheduleId
                          into tsDatails
                          from tsDat in tsDatails.DefaultIfEmpty()
                          join gr_ls in db.GroupLessons on lsDat.LessonId equals gr_ls.LessonId
                          join gr in db.Groups on gr_ls.GroupId equals gr.GroupId
                          where tch.UserId == UserSession.GetUserId
                          where gr.GroupId == id
                          where lsDat.Date <= DateTime.Today
                          orderby lsDat.Date
                          select new IndexTeacherViewModel
                          {
                              LessonId = lsDat.LessonId,
                              GroupName = gr.GroupName,
                              LessonDate = lsDat.Date.ToLongDateString(),
                              LessonTime = tsDat.TimeInterval,
                              SubjectName = sbj.SubjectName + "\n" + $"({ltDat.LessonTypeName})",
                              LessonType = ltDat.LessonTypeName
                          }).ToList();

            return View(lessonList);
        }
        //формируем таблицу для оценивание студентов
        public IActionResult AcademicPerfomance(int id)
        {
            List<StudentPerfomanceViewModel> studentsGroups;
            var groupName = (from ls in db.Lessons
                             join sbj in db.Subjects on ls.SubjectId equals sbj.SubjectId
                             join gr_ls in db.GroupLessons on ls.LessonId equals gr_ls.LessonId
                             join gr in db.Groups on gr_ls.GroupId equals gr.GroupId
                             where ls.LessonId == id
                             select new
                             {
                                 GroupName = gr.GroupName,
                                 SubjectName = sbj.SubjectName,
                                 Date = ls.Date.ToShortDateString()

                             }).FirstOrDefault();
            ViewBag.SubjectName = groupName.SubjectName;
            ViewBag.GroupName = groupName.GroupName;
            ViewBag.Date = groupName.Date;

            List<string> marks = new List<string>
            {
                "+","-","1","2","3","4","5","Зачет","Незачет"
            };
            ViewBag.Marks = new SelectList(marks);
            List<AcademicPerformances> studentPerfomance = db.AcademicPerformances.Where(p => p.LessonId == id).ToList();
            //если есть записи, то всем уже были проставлены оценки
            if (studentPerfomance.Count == 0)
            {
                studentsGroups = (from ls in db.Lessons
                                  join sbj in db.Subjects on ls.SubjectId equals sbj.SubjectId
                                  join gr_ls in db.GroupLessons on ls.LessonId equals gr_ls.LessonId
                                  join gr in db.Groups on gr_ls.GroupId equals gr.GroupId
                                  join st_gr in db.StudentGroups on gr.GroupId equals st_gr.GroupId
                                  join us in db.Users on st_gr.UserId equals us.UserId
                                  where ls.LessonId == id
                                  select new StudentPerfomanceViewModel
                                  {
                                      UserId = us.UserId,
                                      LessonId = id,
                                      FullName = us.LastName + " " + us.FirstName + " "
                                                 + (string.IsNullOrEmpty(us.MiddleName) ? string.Empty : us.MiddleName),
                                  }).ToList();
                return View("AcademicPerfomanceNew",studentsGroups);
            }
            else
            {
                studentsGroups = (from ls in db.Lessons
                                  join ap in db.AcademicPerformances on ls.LessonId equals ap.LessonId
                                  join us in db.Users on ap.UserId equals us.UserId
                                  where ls.LessonId == id
                                  select new StudentPerfomanceViewModel
                                  {
                                      UserId = us.UserId,
                                      AcademicPerformanceId=ap.AcademicPerformanceId,
                                      LessonId = id,
                                      FullName = us.LastName + " " + us.FirstName + " "

ElectronicJournal_WEB/Views/TeacherHomePage/AcademicPerfomanceNew.cshtml
@using ElectronicJournal_WEB.Models.ViewModel
@model List<StudentsPerfomanceViewModel>
@{
    ViewData["Title"] = "AcademicPerfomance";
    Layout = "~/Views/Shared/_LayoutTeacher.cshtml";
}

<h3>Оценивание занятия по @ViewBag.SubjectName гр. @ViewBag.GroupName за @ViewBag.Date</h3>

<div>
    <table border="1">
        <tr>
            <td>ФИО студента</td>
            <td>Оценка</td>
        </tr>
        @using (Html.BeginForm("AcademicPerfomance", "TeacherHomePage", FormMethod.Post))
        {
            @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td>@Model[i].FullName</td>
                    <td>
                        @Html.DropDownListFor(m => m[i].Mark, ViewBag.Marks as SelectList)
                    </td>
                    <td style="display:none;">@Html.HiddenFor(m => m[i].UserId)</td>
                    <td style="display:none;">@Html.HiddenFor(m => m[i].LessonId)</td>
                </tr>
            }
            <tr>
                <td>Заметка к занятию</td>
                <td>@Html.TextArea("note", ViewData)</td>
            </tr>
            <tr>
                <td> <button type="submit">Оценить</button></td>
            </tr>
        }
    </table>
</div>

ElectronicJournal_WEB/Views/TeacherHomePage/AcademicPerfomanceUpdate.cshtml
@using ElectronicJournal_WEB.Models.ViewModel
@model List<StudentsPerfomanceViewModel>
@{
    ViewData["Title"] = "AcademicPerfomance";
    Layout = "~/Views/Shared/_LayoutTeacher.cshtml";
}

<h3>Оценивание занятия по @ViewBag.SubjectName гр. @ViewBag.GroupName за @ViewBag.Date</h3>

<div>
    <table border="1">
        <tr>
            <td><b>ФИО студента</b></td>
            <td><b>Вычтавленная ранее оценка</b></td>
            <td><b>Оценка</b></td>
        </tr>
        @using (Html.BeginForm("AcademicPerfomanceUpdate", "TeacherHomePage",FormMethod.Post))
        {
            @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td>@Model[i].FullName</td>
                    <td>@Model[i].Mark</td>
                    <td>
                        @Html.DropDownListFor(m => m[i].Mark, ViewBag.Marks as SelectList)
                    </td>
                    <td style="display:none;">@Html.HiddenFor(m => m[i].UserId)</td>
                    <td style="display:none;">@Html.HiddenFor(m => m[i].LessonId)</td>
                    <td style="display:none;">@Html.HiddenFor(m => m[i].AcademicPerformanceId)</td>
                </tr>
            }
            <tr>
                <td>Заметка к занятию</td>
                <td>@Html.TextArea("note", ViewData)</td>
            </tr>
            <tr>
                <td> <button type="submit">Обновить</button></td>
            </tr>
        }
        </table>

</div>

ElectronicJournal_WEB/Views/TeacherHomePage/DetailGroupPerformance.cshtml
@using ElectronicJournal_WEB.Models.ViewModel
@model List<StudentsPerfomancesViemModel>

@{
    ViewData["Title"] = "DetailGroupPerformance";
    Layout = "~/Views/Shared/_LayoutTeacher.cshtml";
}

<h3>Успеваемость студентов группы @ViewBag.GroupName по @ViewBag.SubjectName</h3>


<table border="1">
    <tr>
        <th></th>
        @for (int i = 0; i < Model[0].Marks.Count; i++)
        {
            <th>
                @Model[0].Marks[i].Date
                <br/>
                @Model[0].Marks[i].LessonsType
            </th>
        }
    </tr>
    @for (int i = 0; i < Model.Count; i++)
    {
        <tr>
            <td>@Model[i].FullName</td>
            @for (int j = 0; j < Model[i].Marks.Count; j++)
            {
                <td>@Model[i].Marks[j].Mark</td>
            }
        </tr>
    }
</table>

ElectronicJournal_WEB/Views/TeacherHomePage/GroupPerformance.cshtml
@using ElectronicJournal_WEB.Models.DatabaseModel
@model IEnumerable<Groups>
@{
    ViewData["Title"] = "GroupPerformance";
    Layout = "~/Views/Shared/_LayoutTeacher.cshtml";
}


<div>
    <p>Выберите группу</p>
    <table border="1">
        <tr>
            <th><b>Группы</b></th>
        </tr>
        @foreach (Groups item in Model)
        {
            <tr>
                <td><p>@item.GroupName</p></td>
                <td>
                    <input type="submit" value="Выбрать"
                           onclick='location.href="SelectSubject/@item.GroupId"' />
                </td>
            </tr>
        }
    </table>
</div>

ElectronicJournal_WEB/Views/TeacherHomePage/GroupsLessons.cshtml
@using ElectronicJournal_WEB.Models.ViewModel
@model IEnumerable<IndexTeacherViewModel>
@{
    Layout = "_LayoutTeacher";
}

<!DOCTYPE html>

<div>
    <h2>Проведенные занятия</h2>

    <table border="1" style="margin:5px">
        <tr>
            <th><b>Предмет</b></th>
            <th><b>Тип занятия</b></th>
            <th><b>Группа</b></th>
            <th><b>Дата занятия</b></th>
        </tr>
        @foreach (IndexTeacherViewModel item in Model)
        {
            <tr>
                <td>@item.SubjectName</td>
                <td>@item.LessonType</td>
                <td>@item.GroupName</td>
                <td>@item.LessonDate</td>
                <td>
                    <input type="submit" value="Оценить"
                           onclick='location.href="/TeacherHomePage/AcademicPerfomance/@item.LessonId"'/>
                </td>
            </tr>
        }
    </table>
</div>

ElectronicJournal_WEB/Views/TeacherHomePage/Index.cshtml
@using ElectronicJournal_WEB.Models.ViewModel
@model IEnumerable<IndexTeacherViewModel>
@{
    Layout = "_LayoutTeacher";
}

<!DOCTYPE html>

<div>
    <h2>Расписание предстоящих занятий</h2>

    <table border="1">
        <tr>
            <th><b>Предмет</b></th>
            <th><b>Тип занятия</b></th>
            <th><b>Группа</b></th>
            <th><b>Дата занятия</b></th>
            <th><b>Время занятия</b></th>
            <th><b>Аудитория</b></th>
        </tr>
        @foreach (IndexTeacherViewModel p in Model)
        {
        <tr>
            <td>@p.SubjectName</td>
            <td>@p.LessonType</td>
            <td>@p.GroupName</td>
            <td>@p.LessonDate</td>
            <td>@p.LessonTime</td>
            <td>@p.ClassroomName</td>
        </tr>
        }
    </table>
</div>

ElectronicJournal_WEB/Views/TeacherHomePage/SelectSubject.cshtml
@using ElectronicJournal_WEB.Models.ViewModel
@model List<SelectedSubjectViewModel>

@{
    ViewData["Title"] = "SelectSubject";
    Layout = "~/Views/Shared/_LayoutTeacher.cshtml";
}


<h3>Выберите предмет, по которому хотите посмотреть успеваемость группы</h3>

<table border="1">


        @for (int i = 0; i < Model.Count; i++)
        {
            @using (Html.BeginForm("DetailGroupPerformance", "TeacherHomePage", FormMethod.Post))
            {
                <tr>
                    <td>@Model[i].SubjectName</td>
                    <td style="display:none;">@Html.Hidden("SubjectName", Model[i].SubjectName)</td>
                    <td style="display:none;">@Html.Hidden("SubjectId", Model[i].SubjectId)</td>
                    <td style="display:none;">@Html.Hidden("GroupId", Model[i].GroupId)</td>
                    <td> <input type="submit" value="Выбрать" /></td>
                </tr>
            }
        }
    </table>

ElectronicJournal_WEB/Views/TeacherHomePage/StudentAssessment.cshtml
@using ElectronicJournal_WEB.Models.DatabaseModel
@model IEnumerable<Groups>

@{
    ViewData["Title"] = "StudentAssessment";
    Layout = "~/Views/Shared/_LayoutTeacher.cshtml";
}

<div>
    <p>Выберите группу</p>
    <table border="1">
        <tr>
            <th>Группа &nbsp;&nbsp;&nbsp;</th>
        </tr>
        @foreach (Groups item in Model)
        {
            <tr>
                <td><p>@item.GroupName</p></td>
                <td>
                    <input type="submit" value="Выбрать"
                           onclick='location.href="GroupsLessons/@item.GroupId"' />
                </td>
            </tr>
        }
    </table>
</div>